### ISSUE TITLE
[Granblue Fantasy] Grey out unwanted summons

### ISSUE THREAD

**Issue by tenzinhers** [jesuscc1993/user-css#2]
Hello, I'm not well know using GitHub so sorry if I posted on the wrong place

It's possible to make an option to put the name of a summon to be highlighted or gray out the others summons on friends summon?

Like this print, used Kaguya as example

![chrome_Kx2nUun5Xe](https://github.com/jesuscc1993/user-css/assets/15004919/c08d34ee-9e43-4d4c-9474-da09bae21006)

**Comment by jesuscc1993** [comment]
The name is not part of the HTML but the ID is.
You could highlight or dim elements that match or not the summon ID.
But it would barely be configurable; for starters, I can't iterate over lists to output styles. You would only be able to set one summon unless I arbitrarily decided to add X number of setting inputs.
So I don't think I'd be adding that to the style.

You can use this, editting by hand the IDs you don't want to be dimmed:
```
/* ==UserStyle==
@name         Granblue Fantasy - Dim unpreferred summons
@description  Testing grounds for style changes.
@version      2023.08.15.12.24
@author       MetalTxus
@namespace    https://github.com/jesuscc1993/
@license      CC BY-SA 4.0
@preprocessor stylus

==/UserStyle== */

@-moz-document domain("granbluefantasy.jp") {
  .btn-supporter:has(.prt-summon-image:not([data-image^="2040114000"]):not([data-image^="2040003000"])) {
    filter: grayscale(.5) brightness(.66);
  }
}
```

You would need to add an extra `:not([data-image^="SUMMON_ID_GOES_HERE"])` for each summon.
You can find the summon ID on the "Other Data" tab in the wiki.
In this example I'm dimming all summons except for Kaguya and Bahamut.
